title: Kalpa Maker
description: A rookie Engineer
site_title: '@oncu - Kalpa Maker'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kalpa-maker
blog_url: https://www.nagekar.com
email: kalpa777@126.com
keybase_username: kalpa-maker
twitter_username: oncu
reddit_username: kalpa-maker

# absolute or relative
profile_picture: assets/images/weichart.jpg

# Google Analytics ID
google_analytics: 