title: Kalpa Maker name ZXD
description:  >
            A rookie Engineer
            这个人很菜/什么都不会/
            失败人士/兴趣使然的程序员/
            已工作两年，似乎没什么收货。。
site_title: '@oncu - Kalpa Maker'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kalpa-maker
blog_url: https://www.yuque.com/fcant
email: kalpa777@126.com
keybase_username: kalpamaker
twitter_username: oncu
reddit_username: kalpa-maker

# absolute or relative
profile_picture: assets/images/weichart.jpg

# Google Analytics ID
google_analytics: 
